javascripts:
  base:
  - public/javascripts/lib/jquery.js
  - public/javascripts/lib/jquery_ui/*.js
  - public/javascripts/lib/*.js
  - public/javascripts/*.js

stylesheets:
  base:
  - public/stylesheets/lib/jquery_ui/redmond/*.css
  - public/stylesheets/lib/*.css
  - public/stylesheets/*.css

